created first entity - Book
Hryniv/spring-boot-project pull request #1
Opened 2024-07-18 16:48 UTC by Hryniv

created:
- Book class
- Book's dao and service layers 
- DataProcessingException for dao layer
- tests
- aplication.properties files for tests and main program

2024-07-18 17:58 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution

2024-07-18 17:58 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/BookStoreApplication.java
> +            //Book book = new Book();
Uncomment code

2024-07-18 17:58 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/model/Book.java
> +@Data
Don't use `@Data` for entities
Add `@Table` with name

2024-07-19 07:18 UTC, Elena-Bruyako requested changes
see comment

2024-07-19 07:18 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/model/Book.java
> +    public Book() {
Read which annotations `@Data` includes and use required

2024-07-19 18:33 UTC, okuzan approved these changes

2024-07-20 08:52 UTC, merged