Added a search method for the author and title parameters
Hryniv/spring-boot-project pull request #4
Opened 2024-08-26 16:16 UTC by Hryniv

2024-08-28 12:21 UTC, Elena-Bruyako requested changes
see comments

2024-08-28 12:21 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/book/AuthorSpecificationProvider.java
> +        return "author";
create constant

2024-08-28 12:21 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/book/BookSpecificationBuilder.java
> +            sp = sp.and(specificationProviderManager.getSpecificationProvider("author")
create constants

2024-08-28 12:21 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/book/TitleSpecificationProvider.java
> +        return "title";
create constant

2024-08-29 11:26 UTC, Elena-Bruyako requested changes
see comments

2024-08-29 11:26 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/book/AuthorSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> root.get("author").in(param);
use your constant

2024-08-29 11:26 UTC, Elena-Bruyako commented on src/main/java/com/bookstore/repository/book/TitleSpecificationProvider.java
> +        return (root, query, criteriaBuilder) -> (root.get("title").in(param));
same

2024-08-29 18:47 UTC, okuzan approved these changes

2024-08-29 18:47 UTC, okuzan commented on src/main/java/com/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
FYI you can declare mapping list to list in mapstruct too with one line

2024-08-29 18:47 UTC, okuzan commented on src/main/java/com/bookstore/repository/book/BookSpecificationProviderManager.java
> +                .filter(p -> p.getKey().equals(key))
change p to provider

2024-08-30 19:02 UTC, merged